### ISSUE TITLE
implement room class in ruby 

### ISSUE THREAD

**Issue by calvinsettachatgul** [calvinsettachatgul/ch#28]
use the building class to hold rooms
rooms will have some attributes
  people (array of people)
  floor (which floor the room is on)
  room number
  number of doors
  number of windows
  airconditioner?

**Comment by HCode1** [comment]
Getting it ready for review. Working on it

**Comment by calvinsettachatgul** [comment]
Ok



Calvin Settachatgul
5102208405

**Comment by calvinsettachatgul** [comment]
this issue was done by henry
