### ISSUE TITLE
3 topics you would like to discuss and work on

### ISSUE THREAD

**Issue by calvinsettachatgul** [calvinsettachatgul/ch#3]
list 5 topics you would like to cover and we can break down the topics into sub topics
calvin:
algorithms
test driven development tdd
amazon web services
docker
application framework
react

**Comment by calvinsettachatgul** [comment]
hey @HCode1 did you get a chance to decide what you want to work on?

**Comment by calvinsettachatgul** [comment]
@HCode1 did you a get a chance to work on this?

**Comment by HCode1** [comment]
@calvinsettachatgul Ok this is my next task

**Comment by calvinsettachatgul** [comment]
so this is done henry came up with topics
