### ISSUE TITLE
3 algorithms

### ISSUE THREAD

**Issue by calvinsettachatgul** [calvinsettachatgul/ch#4]
find 3 different practice problems from coding websites
hankerrank
leetcode
codewars
cracking the coding interview

**Comment by calvinsettachatgul** [comment]
put the problems inside the algorithms folder.
start a code file and start a test file
example_problem.js
test/example_problem.spec.js

**Comment by calvinsettachatgul** [comment]
useful website
https://www.thatjsdude.com/interview/

https://www.thatjsdude.com/interview/js1.html#isPrime

**Comment by HCode1** [comment]
http://www.thatjsdude.com/interview/js1.html#countingZeros

**Comment by HCode1** [comment]
https://www.interviewcake.com/question/javascript/js-whats-wrong

**Comment by calvinsettachatgul** [comment]
@HCode1 listed 3 problems 
@calvinsettachatgul still needs to do this
